### ISSUE TITLE
Empty comment are creaking project.pbxproj

### ISSUE THREAD

**Issue by meirtz4** [alunny/node-xcode#118]
Hi, i'm using the lib for a long time. Some changes in xcode and other libs and/or tools are adding empty comments into project.pbxproj e.g:

`D80F381A1D5A13ED008BE5F5 /*  */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.swift; name = ""; path = UrlHandlerFactory.swift; sourceTree = "<group>"; };`

After using node-xcode it parsing these empty comments to:
```
		08FB965D6CEC571A065142DC /* View */ = {
			isa = PBXGroup;
			children = (
				{
					value = 08FB96661CEC572F605142DC;
					comment = ;
				},
				{
					value = 08ACBB261CEDF14060D479AA;
					comment = ;
				},
			);
			name = View;
			sourceTree = "<group>";
		};
```

The `comment =;` is breaking the file and i must revert to changes done by node-xcode.

**Comment by imhotep** [comment]
@meirtz4 Can you post a pbxproj that has this problem?

**Comment by meirtz4** [comment]
Actually i can't... sorry! is there something else i can to to help?

**Comment by imhotep** [comment]
Can't reproduce otherwise sorry
