### ISSUE TITLE
simple-plist@0.2.1 (plist@2.0.1) causes Xcode failed to parse the content of the info.plist 

### ISSUE THREAD

**Issue by lovelyelfpop** [alunny/node-xcode#131]
simple-plist@0.2.1 (plist@2.0.1) causes Xcode failed to parse the content of the info.plist 
see [App crashes due to main interface NSMainNibFile~ipad](https://github.com/dpa99c/cordova-custom-config/issues/90)

**Comment by imhotep** [comment]
https://github.com/apache/cordova-node-xcode.git
